// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * @param {string} title
 * @param {Date} start
 * @param {Date} end
 * @param {string} location
 * @param {string} notes
 * @returns {boolean}
 */
function SaveCalendarEvent(
    title?: string,
    start?: Date,
    end?: Date,
    location?: string,
    notes?: string
): Promise<boolean> {
    // BEGIN USER CODE
    // Documentation: https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin
    if (!window.plugins || !window.plugins.calendar) {
        throw new Error("cordova-plugin-calendar not enabled");
    }

    window.plugins.calendar.createEventInteractively(
        title,
        location,
        notes,
        start,
        end,
        () => {
            // This success callback is not called on iOS when the user cancels
        },
        error => {
            throw new Error("Failed to save calendar event: " + error);
        }
    );

    return Promise.resolve(true);
    // END USER CODE
}
